INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES(1,'vinay','password');
INSERT INTO USERS(ID,USERNAME,PASSWORD) VALUES(2,'mahesh','password');


INSERT INTO ROLE(ID,ROLE_NAME) VALUES(1,'ADMIN');

INSERT INTO ROLE(ID,ROLE_NAME) VALUES(2,'USER');

INSERT INTO USER_ROLE(ROLE_ID,USER_ID) VALUES(1,1);
INSERT INTO USER_ROLE(ROLE_ID,USER_ID) VALUES(2,1);

INSERT INTO USER_ROLE(ROLE_ID,USER_ID) VALUES(2,2);